### ISSUE TITLE
various

### ISSUE THREAD

**Issue by SavSanta** [enwawerueli/flask-skeleton#1]
`module 'datetime' has no attribute 'now'`

1. change dt.now to dt.datetime.now in models.py

```
TypeError: configure() takes 0 positional arguments but 1 was given
change config[env].configure(app)
```
2. change  `config[env].configure(app)` to `config[env].configure()` in  app/__init__.py

` Import error: forms`

3.  remove `forms` from `from app import create_app, db, models, forms` in manage.py

There is probably a whole host more but this is what ive seen so far

**Comment by enwawerueli** [comment]
Did a quick look at the issues you pointed out and tried to have them fixed. Let me know if you come across more.
